locals {
  # Canonicalize provider connector IDs before deriving DLP classifications.
  # A connector is unblockable if any duplicate provider record marks it as unblockable.
  all_connector_ids = toset([
    for c in data.powerplatform_connectors.all.connectors : c.id
  ])
  unblockable_connector_ids = toset([
    for c in data.powerplatform_connectors.all.connectors : c.id if c.unblockable
  ])
  blockable_connector_ids = setsubtract(local.all_connector_ids, local.unblockable_connector_ids)

  ##############################################################################
  # SCALAR MODE
  # All scalar locals below are active only when source_policy_name is set.
  # In batch mode (source_policy_names), source_policy_name is null, so
  # selected_policy stays null and all downstream scalar computations are empty.
  ##############################################################################

  # Find the target policy by exact display_name match.
  # Guarded by null check so batch mode never triggers one() on a null input.
  # one() returns null if no match, and errors if more than one policy shares the same name.
  selected_policy = var.source_policy_name != null ? one([
    for p in data.powerplatform_data_loss_prevention_policies.current.policies :
    p if p.display_name == var.source_policy_name
  ]) : null

  policy_exists = local.selected_policy != null

  # Blockable connectors in the source NonBusiness group.
  # res-dlppolicy auto-computes the NonBusiness group from the connector catalog,
  # reclassifying blockable connectors that are currently in NonBusiness to Blocked.
  # coalesce guards against a future provider version returning null instead of empty set.
  connectors_reclassified_to_blocked = local.policy_exists ? [
    for c in coalesce(local.selected_policy.non_business_connectors, []) :
    c.id if contains(local.blockable_connector_ids, c.id)
  ] : []

  # Business connectors, optionally stripping action_rules and endpoint_rules.
  # Fields are projected explicitly to avoid passing extra provider attributes that
  # res-dlppolicy's strict object type would reject.
  # coalesce guards against a future provider version returning null instead of empty set.
  business_connectors = local.policy_exists ? [
    for c in coalesce(local.selected_policy.business_connectors, []) : {
      id                           = c.id
      default_action_rule_behavior = c.default_action_rule_behavior
      action_rules = var.preserve_connector_rules ? [
        for r in c.action_rules : { action_id = r.action_id, behavior = r.behavior }
      ] : []
      endpoint_rules = var.preserve_connector_rules ? [
        for r in c.endpoint_rules : { order = r.order, endpoint = r.endpoint, behavior = r.behavior }
      ] : []
    }
  ] : []

  # Custom connector patterns with wildcard host_url_pattern removed.
  # res-dlppolicy appends host_url_pattern = "*" automatically; its validation rejects it as user input.
  # Fields projected explicitly — res-dlppolicy expects exactly {order, host_url_pattern, data_group}.
  # data_group provider values ("Business", "NonBusiness", "Blocked", "Ignore") verified to match
  # res-dlppolicy's accepted values via `terraform providers schema -json`.
  # coalesce guards against a future provider version returning null instead of empty set.
  custom_connectors_patterns = local.policy_exists ? [
    for p in coalesce(local.selected_policy.custom_connectors_patterns, []) : {
      order            = p.order
      host_url_pattern = p.host_url_pattern
      data_group       = p.data_group
    }
    if p.host_url_pattern != "*"
  ] : []

  # Environment IDs normalised to lowercase and sorted.
  # The environments attribute is a set of strings (environment IDs), not objects.
  # coalesce guards against a future provider version returning null instead of empty set.
  environments_normalised = local.policy_exists ? sort([
    for e in coalesce(local.selected_policy.environments, []) : lower(e)
  ]) : []

  # Generated .tfvars content with exactly the 6 res-dlppolicy variables.
  # Note: timestamp() causes a perpetual plan diff on tfvars_content; this is intentional
  # for a utility module that is run once to migrate a policy.
  # Heredoc cannot be used in a ternary, so content is built with join().
  _tfvars_lines = local.policy_exists ? [
    "# Generated by terraform-powerplatform-utl-dlppolicy-replicator",
    "# Source policy: ${var.source_policy_name}",
    "# Generated at: ${timestamp()}",
    "",
    "display_name                      = ${jsonencode(local.selected_policy.display_name)}",
    "default_connectors_classification = ${jsonencode(local.selected_policy.default_connectors_classification)}",
    "environment_type                  = ${jsonencode(local.selected_policy.environment_type)}",
    "environments                      = ${jsonencode(local.environments_normalised)}",
    "business_connectors               = ${jsonencode(local.business_connectors)}",
    "custom_connectors_patterns        = ${jsonencode(local.custom_connectors_patterns)}",
  ] : []

  tfvars_content = length(local._tfvars_lines) > 0 ? "${join("\n", local._tfvars_lines)}\n" : ""

  ##############################################################################
  # BATCH MODE
  # Active only when source_policy_names is set. All locals below are empty
  # maps/lists in scalar mode (coalesce(var.source_policy_names, []) == []).
  ##############################################################################

  # Number of tenant policies whose display_name matches each requested name.
  # 0 => not_found, 1 => found, >1 => ambiguous.
  _batch_match_counts = {
    for name in coalesce(var.source_policy_names, []) :
    name => length([
      for p in data.powerplatform_data_loss_prevention_policies.current.policies :
      p if p.display_name == name
    ])
  }

  # Matched policy objects — only for names with exactly one tenant match.
  # one() is safe here because the filter condition guarantees exactly one element.
  _batch_policy_map = {
    for name in coalesce(var.source_policy_names, []) :
    name => one([
      for p in data.powerplatform_data_loss_prevention_policies.current.policies :
      p if p.display_name == name
    ])
    if lookup(local._batch_match_counts, name, 0) == 1
  }

  # Per-policy transformed details — same projection/normalisation as scalar mode.
  _batch_details = {
    for name, policy in local._batch_policy_map :
    name => {
      display_name                      = policy.display_name
      default_connectors_classification = policy.default_connectors_classification
      environment_type                  = policy.environment_type
      environments = sort([
        for e in coalesce(policy.environments, []) : lower(e)
      ])
      business_connectors = [
        for c in coalesce(policy.business_connectors, []) : {
          id                           = c.id
          default_action_rule_behavior = c.default_action_rule_behavior
          action_rules = var.preserve_connector_rules ? [
            for r in c.action_rules : { action_id = r.action_id, behavior = r.behavior }
          ] : []
          endpoint_rules = var.preserve_connector_rules ? [
            for r in c.endpoint_rules : { order = r.order, endpoint = r.endpoint, behavior = r.behavior }
          ] : []
        }
      ]
      custom_connectors_patterns = [
        for cp in coalesce(policy.custom_connectors_patterns, []) : {
          order            = cp.order
          host_url_pattern = cp.host_url_pattern
          data_group       = cp.data_group
        }
        if cp.host_url_pattern != "*"
      ]
      connectors_reclassified_to_blocked = [
        for c in coalesce(policy.non_business_connectors, []) :
        c.id if contains(local.blockable_connector_ids, c.id)
      ]
    }
  }

  # Generated .tfvars content per found policy (same format as scalar mode).
  # timestamp() intentionally causes perpetual diffs — see module documentation.
  _batch_tfvars_content = {
    for name, details in local._batch_details :
    name => "${join("\n", [
      "# Generated by terraform-powerplatform-utl-dlppolicy-replicator",
      "# Source policy: ${name}",
      "# Generated at: ${timestamp()}",
      "",
      "display_name                      = ${jsonencode(details.display_name)}",
      "default_connectors_classification = ${jsonencode(details.default_connectors_classification)}",
      "environment_type                  = ${jsonencode(details.environment_type)}",
      "environments                      = ${jsonencode(details.environments)}",
      "business_connectors               = ${jsonencode(details.business_connectors)}",
      "custom_connectors_patterns        = ${jsonencode(details.custom_connectors_patterns)}",
    ])}\n"
  }

  # Aggregate of all connectors_reclassified_to_blocked across every found batch policy.
  # Used by the advisory check block in batch mode; empty in scalar mode.
  _batch_reclassified_connector_ids = distinct(flatten([
    for name, details in local._batch_details :
    details.connectors_reclassified_to_blocked
  ]))

  # Authoritative batch result map keyed by the original requested name.
  # Keys are always the exact requested strings — no sanitisation that could collide.
  batch_results = {
    for name in coalesce(var.source_policy_names, []) :
    name => {
      requested_name = name
      status         = local._batch_match_counts[name] == 0 ? "not_found" : (local._batch_match_counts[name] == 1 ? "found" : "ambiguous")
      found          = local._batch_match_counts[name] == 1

      display_name                       = try(local._batch_details[name].display_name, null)
      default_connectors_classification  = try(local._batch_details[name].default_connectors_classification, null)
      environment_type                   = try(local._batch_details[name].environment_type, null)
      environments                       = try(local._batch_details[name].environments, [])
      business_connectors                = try(local._batch_details[name].business_connectors, [])
      custom_connectors_patterns         = try(local._batch_details[name].custom_connectors_patterns, [])
      connectors_reclassified_to_blocked = try(local._batch_details[name].connectors_reclassified_to_blocked, [])

      # file_path is set only for found policies that have an entry in output_files.
      # Missing and ambiguous policies intentionally receive null — no file is written.
      file_path = local._batch_match_counts[name] == 1 ? lookup(var.output_files, name, null) : null

      tfvars_content = try(local._batch_tfvars_content[name], "")

      migration_summary = {
        source_policy_name             = name
        policy_found                   = local._batch_match_counts[name] == 1
        status                         = local._batch_match_counts[name] == 0 ? "not_found" : (local._batch_match_counts[name] == 1 ? "found" : "ambiguous")
        display_name                   = try(local._batch_details[name].display_name, null)
        business_connector_count       = length(try(local._batch_details[name].business_connectors, []))
        custom_connector_pattern_count = length(try(local._batch_details[name].custom_connectors_patterns, []))
        environment_count              = length(try(local._batch_details[name].environments, []))
        reclassified_connector_count   = length(try(local._batch_details[name].connectors_reclassified_to_blocked, []))
        preserve_connector_rules       = var.preserve_connector_rules
        generation_timestamp           = timestamp()
      }
    }
  }
}
