locals {
  # Map connector ID -> unblockable bool for every connector in the catalog.
  # unblockable = true means the connector CANNOT be placed in the Blocked tier.
  connector_unblockable_map = {
    for c in data.powerplatform_connectors.all.connectors :
    c.id => c.unblockable
  }

  # Find the target policy by exact display_name match.
  # one() returns null if no match, and errors if more than one policy shares the same name.
  selected_policy = one([
    for p in data.powerplatform_data_loss_prevention_policies.current.policies :
    p if p.display_name == var.source_policy_name
  ])

  policy_exists = local.selected_policy != null

  # Blockable connectors in the source NonBusiness group.
  # res-dlppolicy auto-computes the NonBusiness group from the connector catalog,
  # reclassifying blockable connectors that are currently in NonBusiness to Blocked.
  connectors_reclassified_to_blocked = local.policy_exists ? [
    for c in local.selected_policy.non_business_connectors :
    c.id if !lookup(local.connector_unblockable_map, c.id, true)
  ] : []

  # Business connectors, optionally stripping action_rules and endpoint_rules.
  business_connectors = local.policy_exists ? [
    for c in local.selected_policy.business_connectors : {
      id                           = c.id
      default_action_rule_behavior = c.default_action_rule_behavior
      action_rules                 = var.preserve_connector_rules ? c.action_rules : []
      endpoint_rules               = var.preserve_connector_rules ? c.endpoint_rules : []
    }
  ] : []

  # Custom connector patterns with wildcard host_url_pattern removed.
  # res-dlppolicy appends host_url_pattern = "*" automatically; its validation rejects it as user input.
  custom_connectors_patterns = local.policy_exists ? [
    for p in local.selected_policy.custom_connectors_patterns :
    p if p.host_url_pattern != "*"
  ] : []

  # Environment IDs normalised to lowercase and sorted.
  # The environments attribute is a set of strings (environment IDs), not objects.
  environments_normalised = local.policy_exists ? sort([
    for e in local.selected_policy.environments : lower(e)
  ]) : []

  # Generated .tfvars content with exactly the 6 res-dlppolicy variables.
  # Note: timestamp() causes a perpetual plan diff on tfvars_content; this is intentional
  # for a utility module that is run once to migrate a policy.
  # Heredoc cannot be used in a ternary, so content is built with join().
  _tfvars_lines = local.policy_exists ? [
    "# Generated by terraform-powerplatform-utl-dlppolicy-replicator",
    "# Source policy: ${var.source_policy_name}",
    "# Generated at: ${timestamp()}",
    "",
    "display_name                      = ${jsonencode(local.selected_policy.display_name)}",
    "default_connectors_classification = ${jsonencode(local.selected_policy.default_connectors_classification)}",
    "environment_type                  = ${jsonencode(local.selected_policy.environment_type)}",
    "environments                      = ${jsonencode(local.environments_normalised)}",
    "business_connectors               = ${jsonencode(local.business_connectors)}",
    "custom_connectors_patterns        = ${jsonencode(local.custom_connectors_patterns)}",
  ] : []

  tfvars_content = length(local._tfvars_lines) > 0 ? "${join("\n", local._tfvars_lines)}\n" : ""
}